### ISSUE TITLE
the type problem

### ISSUE THREAD

**Issue by gray0302** [y0ast/Variational-Recurrent-Autoencoder#1]
when I run you code, I met the problem is that TypeError: ('An update must have the same type as the original shared variable (shared_var=W_xhe, shared_var.type=CudaNdarrayType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).'. The input is x_train = theano.shared(data.astype(theano.config.floatX), allow_downcast=True, name="x_train"), and the dtype is (96,1,100). I don't change your code, and my theano version is 0.8.2.

**Comment by y0ast** [comment]
Closing this, let me know if there is still a problem.
